include:
    - component: $CI_SERVER_FQDN/home-lab/automations/docker-compose-service-deployment@v1.0.12
      inputs:
          vm-hostname: media.vm.xbhl.intranet
          vm-ssh-username: $SSH_USER
          vm-ssh-private-key: $SSH_PRIVATE_KEY
          service-name: qBittorrent
          container-name: qbittorrent
          container-location: /opt/containers/qbittorrent
          cloudflare-dns-entry-name: qbittorrent.intranet.xbhl.online
          cloudflare-zone-id: $CLOUDFLARE_ZONE_ID
          cloudflare-dns-api-token: $CLOUDFLARE_DNS_API_TOKEN
          container-healthcheck-delay: 30
          delete-existing-container-files: true
