[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/data/logs

[BitTorrent]
Session\AddExtensionToIncompleteFiles=true
Session\AddTorrentStopped=false
Session\AlternativeGlobalDLSpeedLimit=81920
Session\AlternativeGlobalUPSpeedLimit=81920
Session\BandwidthSchedulerEnabled=true
Session\DHTEnabled=false
Session\DefaultSavePath=/downloads
Session\ExcludedFileNames=
Session\LSDEnabled=false
Session\MaxActiveDownloads=10
Session\MaxActiveTorrents=120
Session\MaxActiveUploads=100
Session\MaxConnectionsPerTorrent=150
Session\MaxUploads=100
Session\MaxUploadsPerTorrent=25
Session\PeXEnabled=false
Session\Port=50466
Session\Preallocation=true
Session\QueueingSystemEnabled=false
Session\SSL\Port=47850
Session\ShareLimitAction=Stop
Session\Tags=Points, RSS
Session\TempPath=/downloads/temp
Session\TempPathEnabled=true
Session\UseAlternativeGlobalSpeedLimit=true

[Core]
AutoDeleteAddedTorrentFile=Never

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()
PortForwardingEnabled=false
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
General\Locale=en
MailNotification\req_auth=true
Scheduler\days=Weekday
Scheduler\end_time=@Variant(\0\0\0\xf\x5%q\xa0)
Scheduler\start_time=@Variant(\0\0\0\xf\x1\x9b\xfc\xc0)
WebUI\AuthSubnetWhitelist=10.0.0.0/8, 172.21.0.1/32
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\HTTPS\CertificatePath=/cert/qbittorrent.crt
WebUI\HTTPS\Enabled=true
WebUI\HTTPS\KeyPath=/cert/qbittorrent-private.key
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="@ByteArray(JHyENQgumwSCu+H1+OWR+w==:W/NdDZnFIHT/b3LhJ7AFUeCvZaIaDu22yzgWbDM9ombyU+N7aEP06mcAOS736knTgQLH+cwtUCBWrUDwlnLcdQ==)"
WebUI\Port=10002
WebUI\Username=lbarczynski

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\EnableProcessing=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
Session\EnableProcessing=true
Session\MaxArticlesPerFeed=250
Session\RefreshInterval=1
