services:
    qbittorrent-nox:
        image: ghcr.io/qbittorrent/docker-qbittorrent-nox:${QBITTORRENT_APP_VERSION:?err}
        container_name: qbittorrent
        environment:
            - PUID=${APP_PUID:?err}
            - PGID=${APP_PGID:?err}
            - TZ=${TIME_ZONE:?err}
            - QBT_LEGAL_NOTICE="confirm"
            - QBT_WEBUI_PORT=${QBITTORRENT_WEB_UI_PORT:?err}
            - QBT_TORRENTING_PORT=${QBITTORRENT_CONNECTION_PORT:?err}
        volumes:
            - scripts:/scripts
            - config:/config
            - downloads:/downloads
        ports:
            - ${QBITTORRENT_WEB_UI_PORT:?err}:${QBITTORRENT_WEB_UI_PORT:?err}/tcp
            - ${QBITTORRENT_CONNECTION_PORT:?err}:${QBITTORRENT_CONNECTION_PORT:?err}/tcp
            - ${QBITTORRENT_CONNECTION_PORT:?err}:${QBITTORRENT_CONNECTION_PORT:?err}/udp
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.qbittorrent-router.rule=Host(`${QBITTORRENT_DOMAIN:?err}`)"
            - "traefik.http.routers.qbittorrent-router.entrypoints=websecure"
            - "traefik.http.routers.qbittorrent-router.tls=true"
            - "traefik.http.routers.qbittorrent-router.service=qbittorrent"
            - "traefik.http.services.qbittorrent.loadbalancer.server.url=${QBITTORRENT_SCHEMA:?err}://${QBITTORRENT_HOST:?err}:${QBITTORRENT_WEB_UI_PORT:?err}"
        healthcheck:
            test: /scripts/healthcheck.sh /downloads ${QBITTORRENT_SCHEMA:?err}://localhost:${QBITTORRENT_WEB_UI_PORT:?err}
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped

volumes:
    scripts:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "./scripts"

    config:
        driver: local

    downloads:
        driver: local
        driver_opts:
            type: nfs
            o: addr=${REMOTE_DOWNLOADS_DIR_HOSTNAME:?err},rw,soft,timeo=100,nolock
            device: ${REMOTE_DOWNLOADS_DIR_HOSTNAME:?err}:${REMOTE_DOWNLOADS_DIR_PATH:?err}
